import { PrismaClient } from '@prisma/client';

export async function seedJobs(prisma: PrismaClient) {
  // Build name+type -> id lookup for all education programs
  const allPrograms = await prisma.educationProgram.findMany({ select: { id: true, name: true, type: true, field: true } });
  const pid = (name: string, type: string) => {
    const p = allPrograms.find(x => x.name === name && x.type === type);
    if (!p) throw new Error(`Education program not found: "${name}" (${type})`);
    return p.id;
  };

  // Grouped helpers
  const byType = (...types: string[]) => allPrograms.filter(p => types.includes(p.type)).map(p => p.id);
  const byField = (field: string, ...types: string[]) =>
    allPrograms.filter(p => p.field === field && (types.length === 0 || types.includes(p.type))).map(p => p.id);
  const byFields = (fields: string[], ...types: string[]) =>
    allPrograms.filter(p => fields.includes(p.field) && (types.length === 0 || types.includes(p.type))).map(p => p.id);
  const byName = (name: string, ...types: string[]) =>
    allPrograms.filter(p => p.name === name && (types.length === 0 || types.includes(p.type))).map(p => p.id);

  const anyDegree            = byType('associates', 'bachelors', 'masters', 'doctorate');
  const anyAssociatesOrHigher = byType('associates', 'bachelors', 'masters', 'doctorate');
  const anyBachelorsOrHigher  = byType('bachelors', 'masters', 'doctorate');
  const anyMastersOrHigher    = byType('masters', 'doctorate');

  // PTO helper: days -> time blocks (5 days = 1 time block)
  const pto = (days: number) => Math.round(days / 5);

  const jobs = [
    // ── No-degree jobs ───────────────────────────────────────────────────────
    {
      title: 'Rideshare Driver',
      requirements: { education: 'none', skills: { caution: 60 }, other: 'car <= 10yrs, seats >= 5' },
      baseSalary: 0, raiseSchedule: {}, timeBlocks: 0, stressLevel: 10, ptoTimeBlocks: 0,
      fullTime: true, partTime: true, seasonal: false,
      benefits: { incomePerTimeBlock: 1000, bonuses: { charisma70: 600, organization50: 150, patience50: 150, caution80: 600 }, gasCostIncreasePct: 1.5, canBeSecondJob: true },
      annualGains: {}, location: 'both', hasPension: false, easeOfGetting: 1,
    },
    {
      title: 'Cashier',
      requirements: { education: 'none', skills: {} },
      baseSalary: 25000, raiseSchedule: { type: 'SS' }, timeBlocks: 20, stressLevel: 30, ptoTimeBlocks: 0,
      fullTime: true, partTime: true, seasonal: true,
      benefits: { shoppingDiscountPct: 10, canBeSecondJob: true },
      annualGains: { communication: 2, math: 1 }, location: 'both', hasPension: false, easeOfGetting: 1,
    },
    {
      title: 'Store Manager',
      requirements: {
        educationIds: [
          ...byFields(['Math'], 'associates', 'bachelors').filter(id => ['Business','Finance'].includes(allPrograms.find(p => p.id === id)!.name)),
        ],
        educationAlternative: { yearsExperience: 15, jobTitle: 'Cashier' },
        skills: { organization: 50, sociability: 60, communication: 55 },
      },
      baseSalary: 45000, raiseSchedule: { type: 'SS' }, timeBlocks: 20, stressLevel: 35, ptoTimeBlocks: pto(5),
      fullTime: true, partTime: false, seasonal: false,
      benefits: { shoppingDiscountPct: 20 },
      annualGains: { organization: 3, sociability: 4, communication: 4 }, location: 'both', hasPension: false, easeOfGetting: 3,
    },
    {
      title: 'Waiter',
      requirements: { education: 'none', skills: { sociability: 30 } },
      baseSalary: 5000, raiseSchedule: { type: 'SS' }, timeBlocks: 20, stressLevel: 40, ptoTimeBlocks: 0,
      fullTime: true, partTime: true, seasonal: true,
      benefits: { baseTips: 5000, tipsPerSkill5pct: 3000, canBeSecondJob: true },
      annualGains: { sociability: 3 }, location: 'both', hasPension: false, easeOfGetting: 1,
    },
    {
      title: 'Restaurant Manager',
      requirements: {
        educationIds: byFields(['Math'], 'associates', 'bachelors').filter(id => ['Business','Finance'].includes(allPrograms.find(p => p.id === id)!.name)),
        educationAlternative: { yearsExperience: 15, jobTitle: 'Waiter' },
        skills: { organization: 60, sociability: 70, communication: 55 },
      },
      baseSalary: 50000, raiseSchedule: { type: 'MM' }, timeBlocks: 20, stressLevel: 40, ptoTimeBlocks: pto(10),
      fullTime: true, partTime: false, seasonal: false,
      benefits: {},
      annualGains: { organization: 3, sociability: 4, communication: 4 }, location: 'both', hasPension: false, easeOfGetting: 2,
    },
    {
      title: 'Youth Program Staff Member',
      requirements: { education: 'none', skills: { charisma: 50, patience: 50, goodWithKids: 50 }, certifications: ['CPR'] },
      baseSalary: 40000, raiseSchedule: { type: 'SS' }, timeBlocks: 20, stressLevel: 30, ptoTimeBlocks: 0,
      fullTime: true, partTime: true, seasonal: true,
      benefits: { canBeSecondJob: true },
      annualGains: { charisma: 3, patience: 5, goodWithKids: 5 }, location: 'both', hasPension: false, easeOfGetting: 2,
    },
    {
      title: 'Youth Program Director',
      requirements: {
        educationIds: byFields(['Math','Humanities'], 'associates', 'bachelors').filter(id => ['Business','Psychology','English','Sociology','Education'].includes(allPrograms.find(p => p.id === id)!.name)),
        educationAlternative: { yearsExperience: 15, jobTitle: 'Youth Program Staff Member' },
        skills: { creativity: 60, organization: 60, communication: 55 }, certifications: ['CPR'],
      },
      baseSalary: 50000, raiseSchedule: { type: 'MS' }, timeBlocks: 20, stressLevel: 35, ptoTimeBlocks: pto(10),
      fullTime: true, partTime: false, seasonal: false,
      benefits: {},
      annualGains: { creativity: 3, organization: 3, communication: 4 }, location: 'both', hasPension: true, easeOfGetting: 3,
    },
    {
      title: 'Realtor',
      requirements: { education: 'none', skills: { charisma: 80, sociability: 80, organization: 60 }, other: 'cert on job; training first 6mo yr1' },
      baseSalary: 0, raiseSchedule: { type: 'commission', formula: 'roll_2_5_x_15000', scaleUpEvery5yrs: 3 }, timeBlocks: 20, stressLevel: 40, ptoTimeBlocks: 0,
      fullTime: true, partTime: false, seasonal: false,
      benefits: {},
      annualGains: { charisma: 2, sociability: 2, organization: 2 }, location: 'suburb', hasPension: false, easeOfGetting: 1,
    },
    {
      title: 'Construction Worker',
      requirements: { education: 'none', skills: { caution: 70, physicalAbility: 70, homeRepair: 5 } },
      baseSalary: 25000, raiseSchedule: { type: 'MS' }, timeBlocks: 20, stressLevel: 40, ptoTimeBlocks: 0,
      fullTime: true, partTime: false, seasonal: true,
      benefits: {},
      annualGains: { physicalAbility: 3, homeRepair: 4 }, location: 'both', hasPension: false, easeOfGetting: 1,
    },
    {
      title: 'Construction Manager',
      requirements: {
        educationIds: byFields(['Humanities','Math'], 'bachelors').filter(id => ['Architecture','Finance','Business'].includes(allPrograms.find(p => p.id === id)!.name)),
        educationAlternative: { yearsExperience: 10, jobTitle: 'Construction Worker' },
        skills: { organization: 70, communication: 65, technology: 20 },
      },
      baseSalary: 75000, raiseSchedule: { type: 'SM' }, timeBlocks: 20, stressLevel: 55, ptoTimeBlocks: pto(10),
      fullTime: true, partTime: false, seasonal: false,
      benefits: {},
      annualGains: { organization: 3, communication: 3 }, location: 'both', hasPension: false, easeOfGetting: 3,
    },
    {
      title: 'Bartender',
      requirements: { education: 'none', skills: { charisma: 70, sociability: 50, patience: 50, organization: 35 }, minAge: 21 },
      baseSalary: 25000, raiseSchedule: { type: 'SS' }, timeBlocks: 20, stressLevel: 40, ptoTimeBlocks: 0,
      fullTime: true, partTime: true, seasonal: true,
      benefits: { baseTips: 35000, tipsPerSkillAvg5pct: 5000, canBeSecondJob: true, noChildcareIfSpouseIsBartender: true },
      annualGains: { sociability: 2, patience: 2, organization: 2 }, location: 'city', hasPension: false, easeOfGetting: 3,
    },
    {
      title: 'Bar Manager',
      requirements: {
        educationIds: byFields(['Math'], 'bachelors').filter(id => ['Finance','Business'].includes(allPrograms.find(p => p.id === id)!.name)),
        educationAlternative: { yearsExperience: 10, jobTitle: 'Bartender' },
        skills: { organization: 60, communication: 55 },
      },
      baseSalary: 40000, raiseSchedule: { type: 'MM' }, timeBlocks: 20, stressLevel: 35, ptoTimeBlocks: pto(10),
      fullTime: true, partTime: false, seasonal: false,
      benefits: {},
      annualGains: { organization: 2, communication: 3 }, location: 'city', hasPension: false, easeOfGetting: 4,
    },
    {
      title: 'Mail Carrier',
      requirements: { education: 'none', skills: { organization: 60, caution: 55 } },
      baseSalary: 35000, raiseSchedule: { type: 'SS' }, timeBlocks: 20, stressLevel: 30, ptoTimeBlocks: pto(15),
      fullTime: true, partTime: false, seasonal: false,
      benefits: {},
      annualGains: { organization: 2 }, location: 'city', hasPension: true, easeOfGetting: 3,
    },
    {
      title: 'Secretary',
      requirements: { education: 'none', skills: { organization: 70, communication: 40, sociability: 60, technology: 7 } },
      baseSalary: 25000, raiseSchedule: { type: 'SS' }, timeBlocks: 20, stressLevel: 30, ptoTimeBlocks: pto(10),
      fullTime: true, partTime: false, seasonal: false,
      benefits: {},
      annualGains: { organization: 3, communication: 2, sociability: 2 }, location: 'city', hasPension: false, easeOfGetting: 4,
    },
    {
      title: 'Security Guard',
      requirements: { education: 'none', skills: { bravery: 50, patience: 40, caution: 65, physicalAbility: 70 }, certifications: ['CPR'] },
      baseSalary: 25000, raiseSchedule: { type: 'MS' }, timeBlocks: 20, stressLevel: 35, ptoTimeBlocks: 0,
      fullTime: true, partTime: true, seasonal: false,
      benefits: { canBeSecondJob: true },
      annualGains: { patience: 1 }, location: 'city', hasPension: false, easeOfGetting: 1,
    },
    {
      title: 'Landscaper',
      requirements: { education: 'none', skills: { organization: 35, caution: 65, physicalAbility: 40 } },
      baseSalary: 25000, raiseSchedule: { type: 'SS' }, timeBlocks: 20, stressLevel: 10, ptoTimeBlocks: 0,
      fullTime: true, partTime: true, seasonal: false,
      benefits: {},
      annualGains: { organization: 2, physicalAbility: 1 }, location: 'suburb', hasPension: false, easeOfGetting: 1,
    },
    {
      title: 'Flight Attendant',
      requirements: { education: 'none', skills: { organization: 50, sociability: 70, compassion: 50, patience: 60, caution: 65 }, certifications: ['CPR'] },
      baseSalary: 40000, raiseSchedule: { type: 'MS' }, timeBlocks: 16, stressLevel: 40, ptoTimeBlocks: pto(10),
      fullTime: true, partTime: true, seasonal: false,
      benefits: { travelTickets: { count: 8, discountPct: 80 }, ptoIncreasePer10yrs: 4 },
      annualGains: { organization: 2, sociability: 4, compassion: 1, patience: 5 }, location: 'city', hasPension: false, easeOfGetting: 5,
    },
    {
      title: 'Fitness Instructor',
      requirements: { education: 'none', skills: { health: 90, charisma: 60, organization: 30, physicalAbility: 60 } },
      baseSalary: 40000, raiseSchedule: { type: 'MS' }, timeBlocks: 20, stressLevel: 20, ptoTimeBlocks: pto(10),
      fullTime: true, partTime: true, seasonal: false,
      benefits: { freeGymMembership: true, canBeSecondJob: true },
      annualGains: { health: 1, organization: 1, physicalAbility: 2 }, location: 'city', hasPension: false, easeOfGetting: 3,
    },
    {
      title: 'Hair Stylist',
      requirements: { educationIds: [pid('Beauty School', 'vocational')], skills: { caution: 60, organization: 30 } },
      baseSalary: 25000, raiseSchedule: { type: 'SS' }, timeBlocks: 20, stressLevel: 40, ptoTimeBlocks: pto(10),
      fullTime: true, partTime: true, seasonal: false,
      benefits: {},
      annualGains: { organization: 2, creativity: 2 }, location: 'city', hasPension: false, easeOfGetting: 4,
    },
    {
      title: 'Exterminator',
      requirements: { education: 'none', skills: { bravery: 50, caution: 65 }, other: 'license on job; training first 6mo yr1' },
      baseSalary: 30000, raiseSchedule: { type: 'SS' }, timeBlocks: 20, stressLevel: 30, ptoTimeBlocks: 0,
      fullTime: true, partTime: false, seasonal: false,
      benefits: { pestDiscountPct: 70, ptoProg: { yr1: 0, yr2: 1, yr3to5: 2, yr6to10: 3, yr11plus: 4 } },
      annualGains: {}, location: 'suburb', hasPension: false, easeOfGetting: 1,
    },
    {
      title: 'Mechanic',
      requirements: { educationIds: [pid('Automotive Technician School', 'vocational')], skills: { organization: 30, physicalAbility: 60, caution: 70, homeRepair: 60 } },
      baseSalary: 35000, raiseSchedule: { type: 'SS' }, timeBlocks: 20, stressLevel: 30, ptoTimeBlocks: pto(10),
      fullTime: true, partTime: false, seasonal: false,
      benefits: { autoMaintenanceDiscountPct: 80 },
      annualGains: { organization: 1, homeRepair: 5 }, location: 'suburb', hasPension: false, easeOfGetting: 4,
    },
    {
      title: 'Plumber',
      requirements: { educationIds: [pid('Plumbing Trade School', 'vocational')], skills: { organization: 30, caution: 60, physicalAbility: 40, homeRepair: 60 } },
      baseSalary: 40000, raiseSchedule: { type: 'SS', noRaisesUntilYr: 2 }, timeBlocks: 20, stressLevel: 30, ptoTimeBlocks: 0,
      fullTime: true, partTime: false, seasonal: false,
      benefits: { plumbingDiscountPct: 85, ptoAfterYr3: pto(10) },
      annualGains: { organization: 1, homeRepair: 5 }, location: 'suburb', hasPension: false, easeOfGetting: 2,
    },
    {
      title: 'Electrician',
      requirements: { educationIds: [pid('Electrician Trade School', 'vocational')], skills: { caution: 80, organization: 30, homeRepair: 60 } },
      baseSalary: 30000, raiseSchedule: { type: 'SS', noRaisesUntilYr: 4 }, timeBlocks: 20, stressLevel: 30, ptoTimeBlocks: pto(5),
      fullTime: true, partTime: false, seasonal: false,
      benefits: { electricalDiscountPct: 80 },
      annualGains: { organization: 1, homeRepair: 5 }, location: 'suburb', hasPension: false, easeOfGetting: 3,
    },
    {
      title: 'Carpenter',
      requirements: { educationIds: [pid('Carpentry Trade School', 'vocational')], skills: { organization: 30, physicalAbility: 50, caution: 70, homeRepair: 60 } },
      baseSalary: 30000, raiseSchedule: { type: 'SS', noRaisesUntilYr: 4 }, timeBlocks: 20, stressLevel: 30, ptoTimeBlocks: 0,
      fullTime: true, partTime: false, seasonal: false,
      benefits: { housingRepairDiscountPct: 40, ptoProg: { yr5to7: 1, yr8to17: 2, yr18plus: 3 } },
      annualGains: { organization: 1, homeRepair: 5 }, location: 'suburb', hasPension: false, easeOfGetting: 2,
    },
    {
      title: 'Firefighter',
      requirements: { educationIds: [pid('Firefighter Academy', 'vocational')], skills: { physicalAbility: 80, bravery: 80, caution: 90, organization: 80, stressTolerance: 80, communication: 80, health: 90 }, certifications: ['CPR'] },
      baseSalary: 40000, raiseSchedule: { type: 'SM' }, timeBlocks: 24, stressLevel: 60, ptoTimeBlocks: pto(20),
      fullTime: true, partTime: false, seasonal: false,
      benefits: { freeGymMembership: true, ptoAfterYr16: pto(30) },
      annualGains: { physicalAbility: 3, bravery: 2, organization: 2, stressTolerance: 5, communication: 2 }, location: 'both', hasPension: true, easeOfGetting: 4,
    },
    {
      title: 'Police Officer',
      requirements: { educationIds: [pid('Police Academy', 'certificate')], skills: { bravery: 70, organization: 40, patience: 60, caution: 75, analysis: 20, stressTolerance: 80, physicalAbility: 75, communication: 70, health: 90 }, certifications: ['CPR'] },
      baseSalary: 40000, raiseSchedule: { type: 'SM' }, timeBlocks: 20, stressLevel: 60, ptoTimeBlocks: pto(15),
      fullTime: true, partTime: false, seasonal: false,
      benefits: {},
      annualGains: { organization: 2, patience: 2, analysis: 2, stressTolerance: 1, communication: 2 }, location: 'both', hasPension: true, easeOfGetting: 3,
    },
    {
      title: 'Chef',
      requirements: { educationIds: [pid('Culinary School', 'vocational')], skills: { organization: 65, caution: 65 } },
      baseSalary: 35000, raiseSchedule: { type: 'SM' }, timeBlocks: 24, stressLevel: 50, ptoTimeBlocks: pto(10),
      fullTime: true, partTime: false, seasonal: false,
      benefits: {},
      annualGains: { organization: 2 }, location: 'both', hasPension: false, easeOfGetting: 4,
    },
    {
      title: 'Photographer',
      requirements: { educationIds: byName('Photography'), skills: { creativity: [50,60,70,80,90], charisma: 60, technology: [7,20,30,50,100] } },
      baseSalary: 0, raiseSchedule: { type: 'SM', byDegree: { none: 20000, cc: 30000, bachelors: 35000, masters: 45000, phd: 65000 } }, timeBlocks: 20, stressLevel: 20, ptoTimeBlocks: 0,
      fullTime: true, partTime: true, seasonal: true,
      benefits: { canBeSecondJob: true },
      annualGains: { creativity: 1, charisma: 2 }, location: 'both', hasPension: false, easeOfGetting: 3,
    },
    {
      title: 'Artist',
      requirements: { educationIds: [...byName('Art'), ...byName('Material Art'), ...byName('Digital Art')], skills: { creativity: [55,65,75,85,95], art: [8,20,30,50,100] } },
      baseSalary: 0, raiseSchedule: { type: 'SM', byDegree: { none: 30000, cc: 40000, bachelors: 50000, masters: 60000, phd: 80000 } }, timeBlocks: 20, stressLevel: 20, ptoTimeBlocks: 0,
      fullTime: true, partTime: false, seasonal: false,
      benefits: {},
      annualGains: { creativity: 2, art: 3 }, location: 'city', hasPension: false, easeOfGetting: 3,
    },
    {
      title: 'Dancer',
      requirements: { educationIds: byName('Dance'), skills: { creativity: [0,0,0,60,80], physicalAbility: 65 } },
      baseSalary: 0, raiseSchedule: { type: 'SM', byDegree: { none: 25000, cc: 35000, bachelors: 50000, masters: 60000, phd: 75000 } }, timeBlocks: 20, stressLevel: 20, ptoTimeBlocks: 0,
      fullTime: true, partTime: false, seasonal: false,
      benefits: {},
      annualGains: { physicalAbility: 1 }, location: 'city', hasPension: false, easeOfGetting: 3,
    },
    {
      title: 'Graphic Designer',
      requirements: { educationIds: [...byName('Graphic Design'), ...byName('Digital Art')], skills: { creativity: [60,70,80,95], technology: [20,30,50,100] } },
      baseSalary: 0, raiseSchedule: { type: 'MM', byDegree: { cc: 40000, bachelors: 50000, masters: 60000, phd: 70000 } }, timeBlocks: 20, stressLevel: 20, ptoTimeBlocks: pto(10),
      fullTime: true, partTime: true, seasonal: false,
      benefits: { canBeSecondJob: true },
      annualGains: { creativity: 2, technology: 1 }, location: 'city', hasPension: false, easeOfGetting: 3,
    },
    {
      title: 'Teaching Assistant',
      requirements: { educationIds: [...byType('masters'), ...byType('doctorate')], skills: {} },
      baseSalary: 30000, raiseSchedule: {}, timeBlocks: 10, stressLevel: 20, ptoTimeBlocks: 0,
      fullTime: false, partTime: true, seasonal: true,
      benefits: { rollsOverYrToYr: true },
      annualGains: { communication: 5, organization: 3 }, location: 'city', hasPension: false, easeOfGetting: 2,
    },
    {
      title: 'Teacher',
      requirements: { educationIds: [pid('Teaching Credential', 'certificate')], skills: { compassion: 70, creativity: 50, organization: 80, patience: 80, goodWithKids: 80, communication: 70, technology: 15 }, certifications: ['CPR'] },
      baseSalary: 50000, raiseSchedule: { type: 'SS', mastersBonus: 100000 }, timeBlocks: 16, stressLevel: 45, ptoTimeBlocks: 0,
      unpaidTimeOff: 4, fullTime: true, partTime: true, seasonal: false,
      benefits: { canBeSecondJob: true },
      annualGains: { creativity: 2, organization: 2, patience: 2, goodWithKids: 2, communication: 3, technology: 1 }, location: 'both', hasPension: true, easeOfGetting: 4,
    },
    {
      title: 'Professor',
      requirements: { educationIds: byType('doctorate'), skills: { analysis: 100, writing: 100 } },
      baseSalary: 80000, raiseSchedule: { type: 'SM' }, timeBlocks: 16, stressLevel: 25, ptoTimeBlocks: 0,
      unpaidTimeOff: 4, fullTime: true, partTime: true, seasonal: false,
      benefits: { canBeSecondJob: true },
      annualGains: {}, location: 'city', hasPension: true, easeOfGetting: 5,
    },
    {
      title: 'Principal',
      requirements: { educationIds: byName('Education', 'masters', 'doctorate'), skills: { organization: 100, communication: 90 }, other: 'must have been teacher/professor 2yrs combined' },
      baseSalary: 60000, raiseSchedule: { type: 'SM' }, timeBlocks: 20, stressLevel: 50, ptoTimeBlocks: 0,
      fullTime: true, partTime: false, seasonal: false,
      benefits: {},
      annualGains: { communication: 2 }, location: 'both', hasPension: true, easeOfGetting: 4,
    },
    {
      title: 'Dean',
      requirements: { educationIds: byName('Education', 'doctorate'), skills: { organization: 100, communication: 100 }, other: 'must have been principal 5yrs' },
      baseSalary: 90000, raiseSchedule: { type: 'SM' }, timeBlocks: 20, stressLevel: 40, ptoTimeBlocks: 0,
      fullTime: true, partTime: false, seasonal: false,
      benefits: {},
      annualGains: {}, location: 'city', hasPension: true, easeOfGetting: 4,
    },
    {
      title: 'Lawyer',
      requirements: { educationIds: [pid('Law School', 'certificate')], skills: { perseverance: 70, charisma: 80, organization: 70, analysis: 65, communication: 90 } },
      baseSalary: 80000, raiseSchedule: { type: 'ML' }, timeBlocks: 28, stressLevel: 70, ptoTimeBlocks: pto(20),
      fullTime: true, partTime: false, seasonal: false,
      benefits: {},
      annualGains: { organization: 1, analysis: 2, communication: 2 }, location: 'city', hasPension: false, easeOfGetting: 3,
    },
    {
      title: 'School Counselor',
      requirements: { educationIds: [...byName('Psychology','masters','doctorate'), ...byName('Education','masters','doctorate'), ...byName('Sociology','masters','doctorate')], skills: { sociability: 70, compassion: 75, organization: 70, patience: 60, goodWithKids: 80 }, certifications: ['CPR'] },
      baseSalary: 0, raiseSchedule: { type: 'SS', byDegree: { masters: 50000, phd: 80000 } }, timeBlocks: 16, stressLevel: 50, ptoTimeBlocks: 0,
      unpaidTimeOff: 4, fullTime: true, partTime: true, seasonal: false,
      benefits: {},
      annualGains: { compassion: 2, patience: 1, goodWithKids: 2 }, location: 'both', hasPension: true, easeOfGetting: 4,
    },
    {
      title: 'Architect',
      requirements: { educationIds: byName('Architecture', 'bachelors', 'masters', 'doctorate'), skills: { creativity: [40,50,60], organization: [40,50,60], homeRepair: [20,30,40] } },
      baseSalary: 0, raiseSchedule: { type: 'MS', byDegree: { bachelors: 50000, masters: 70000, phd: 90000 } }, timeBlocks: 20, stressLevel: 30, ptoTimeBlocks: pto(10),
      fullTime: true, partTime: false, seasonal: false,
      benefits: {},
      annualGains: {}, location: 'city', hasPension: false, easeOfGetting: 5,
    },
    {
      title: 'Linguist',
      requirements: { educationIds: byName('Linguistics', 'bachelors', 'masters', 'doctorate'), skills: { organization: [50,65,80], analysis: [30,50,100], writing: [30,50,100] } },
      baseSalary: 0, raiseSchedule: { type: 'MS', byDegree: { bachelors: 55000, masters: 75000, phd: 90000 } }, timeBlocks: 20, stressLevel: 30, ptoTimeBlocks: pto(10),
      fullTime: true, partTime: false, seasonal: false,
      benefits: {},
      annualGains: { analysis: 2, writing: 2 }, location: 'city', hasPension: false, easeOfGetting: 5,
    },
    {
      title: 'Archaeologist',
      requirements: { educationIds: byName('Archaeology', 'bachelors', 'masters', 'doctorate'), skills: { organization: [50,65,80], patience: 75, caution: 60, analysis: [30,50,100], communication: [30,50,100], writing: [30,50,100], technology: 15 } },
      baseSalary: 0, raiseSchedule: { type: 'MS', byDegree: { bachelors: 55000, masters: 65000, phd: 75000 } }, timeBlocks: 20, stressLevel: 40, ptoTimeBlocks: 0,
      fullTime: true, partTime: false, seasonal: false,
      benefits: {},
      annualGains: { patience: 2, communication: 1, writing: 1 }, location: 'city', hasPension: false, easeOfGetting: 5,
    },
    {
      title: 'Nurse',
      requirements: { educationIds: byName('Nursing', 'bachelors', 'masters', 'doctorate'), skills: { compassion: 65, organization: 85, patience: 70, caution: 85, communication: 70, technology: 20, science: 30 }, certifications: ['CPR'] },
      baseSalary: 0, raiseSchedule: { type: 'MS', byDegree: { bachelors: 70000, masters: 85000, phd: 100000 } }, timeBlocks: 24, stressLevel: 65, ptoTimeBlocks: pto(10),
      fullTime: true, partTime: true, seasonal: false,
      benefits: {},
      annualGains: { compassion: 1, communication: 2 }, location: 'both', hasPension: false, easeOfGetting: 2,
    },
    {
      title: 'General Practitioner',
      requirements: { educationIds: [pid('General Medical Residency', 'certificate')], skills: { compassion: 40, organization: 50, caution: 85, analysis: 75, communication: 75, technology: 25, science: 100 }, certifications: ['CPR'] },
      baseSalary: 100000, raiseSchedule: { type: 'ML' }, timeBlocks: 24, stressLevel: 70, ptoTimeBlocks: pto(10),
      fullTime: true, partTime: false, seasonal: false,
      benefits: {},
      annualGains: { analysis: 2, communication: 1 }, location: 'both', hasPension: false, easeOfGetting: 5,
    },
    {
      title: 'Surgeon',
      requirements: { educationIds: [pid('Surgical Residency', 'certificate')], skills: { organization: 50, caution: 90, stressTolerance: 80, analysis: 65, communication: 60, technology: 30, science: 100 }, certifications: ['CPR'] },
      baseSalary: 180000, raiseSchedule: { type: 'ML' }, timeBlocks: 28, stressLevel: 70, ptoTimeBlocks: pto(10),
      fullTime: true, partTime: false, seasonal: false,
      benefits: {},
      annualGains: { stressTolerance: 2, analysis: 1 }, location: 'both', hasPension: false, easeOfGetting: 5,
    },
    {
      title: 'Chiropractor',
      requirements: { educationIds: [pid('Chiropractic School', 'certificate')], skills: { caution: 85, analysis: 35, technology: 15, science: 50 }, certifications: ['CPR'] },
      baseSalary: 70000, raiseSchedule: { type: 'MM' }, timeBlocks: 20, stressLevel: 50, ptoTimeBlocks: 0,
      fullTime: true, partTime: false, seasonal: false,
      benefits: { ptoAfterYr1: pto(5) },
      annualGains: { analysis: 1 }, location: 'city', hasPension: false, easeOfGetting: 4,
    },
    {
      title: 'Psychologist',
      requirements: { educationIds: byName('Psychology', 'masters', 'doctorate'), skills: { compassion: 75, patience: 90, sociability: 90, analysis: 75, communication: 75, science: 50 } },
      baseSalary: 0, raiseSchedule: { type: 'MM', byDegree: { masters: 80000, phd: 100000 } }, timeBlocks: 20, stressLevel: 50, ptoTimeBlocks: pto(30),
      fullTime: true, partTime: false, seasonal: false,
      benefits: {},
      annualGains: { analysis: 2, communication: 2 }, location: 'city', hasPension: false, easeOfGetting: 4,
    },
    {
      title: 'Dentist',
      requirements: { educationIds: [pid('Dental School', 'certificate')], skills: { organization: 50, caution: 70, analysis: 35, goodWithKids: 70, technology: 15, science: 50 }, certifications: ['CPR'] },
      baseSalary: 120000, raiseSchedule: { type: 'MM' }, timeBlocks: 20, stressLevel: 50, ptoTimeBlocks: pto(10),
      fullTime: true, partTime: false, seasonal: false,
      benefits: {},
      annualGains: { analysis: 1, goodWithKids: 2 }, location: 'city', hasPension: false, easeOfGetting: 3,
    },
    {
      title: 'Physical Therapist',
      requirements: { educationIds: [pid('Physical Therapy School', 'certificate')], skills: { compassion: 65, patience: 70, caution: 70, sociability: 75, analysis: 40, communication: 70, science: 50 }, certifications: ['CPR'] },
      baseSalary: 70000, raiseSchedule: { type: 'MM' }, timeBlocks: 20, stressLevel: 50, ptoTimeBlocks: pto(10),
      fullTime: true, partTime: false, seasonal: false,
      benefits: {},
      annualGains: { analysis: 1, communication: 1 }, location: 'city', hasPension: false, easeOfGetting: 3,
    },
    {
      title: 'Accountant',
      requirements: { educationIds: [...byName('Economics','bachelors','masters','doctorate'), ...byName('Statistics','bachelors','masters','doctorate'), ...byName('Finance','bachelors','masters','doctorate'), ...byName('Business','bachelors','masters','doctorate')], skills: { organization: 85, caution: 70, stressTolerance: 75, analysis: 25, math: 30, technology: 15 } },
      baseSalary: 0, raiseSchedule: { type: 'MM', byDegree: { bachelors: 50000, masters: 70000, phd: 85000 } }, timeBlocks: 24, stressLevel: 60, ptoTimeBlocks: pto(10),
      fullTime: true, partTime: true, seasonal: false,
      benefits: {},
      annualGains: { organization: 2, analysis: 1 }, location: 'city', hasPension: false, easeOfGetting: 2,
    },
    {
      title: 'Economist',
      requirements: { educationIds: [...byName('Economics','masters','doctorate'), ...byName('Business','masters','doctorate')], skills: { organization: 70, analysis: 70, communication: 75, math: 50, writing: 50, technology: 15 } },
      baseSalary: 0, raiseSchedule: { type: 'FS', byDegree: { masters: 80000, phd: 100000 } }, timeBlocks: 20, stressLevel: 30, ptoTimeBlocks: pto(10),
      fullTime: true, partTime: false, seasonal: false,
      benefits: {},
      annualGains: { analysis: 2, communication: 2, writing: 1 }, location: 'city', hasPension: false, easeOfGetting: 4,
    },
    {
      title: 'Actuary',
      requirements: { educationIds: [...byName('Economics','bachelors','masters','doctorate'), ...byName('Statistics','bachelors','masters','doctorate'), ...byName('Finance','bachelors','masters','doctorate'), ...byName('Business','bachelors','masters','doctorate')], skills: { caution: 60, math: 30, analysis: 20, technology: 15 } },
      baseSalary: 0, raiseSchedule: { type: 'MS', byDegree: { bachelors: 65000, masters: 85000, phd: 100000 } }, timeBlocks: 20, stressLevel: 30, ptoTimeBlocks: pto(15),
      fullTime: true, partTime: true, seasonal: false,
      benefits: {},
      annualGains: { analysis: 1 }, location: 'city', hasPension: false, easeOfGetting: 4,
    },
    {
      title: 'Data Scientist',
      requirements: { educationIds: [...byName('Data Science','bachelors','masters','doctorate'), ...byName('Computer Science','bachelors','masters','doctorate'), ...byName('Statistics','bachelors','masters','doctorate')], skills: { communication: 75, math: 40, analysis: 40, technology: 30 } },
      baseSalary: 0, raiseSchedule: { type: 'FM', byDegree: { bachelors: 85000, masters: 100000, phd: 120000 } }, timeBlocks: 20, stressLevel: 30, ptoTimeBlocks: pto(20),
      fullTime: true, partTime: true, seasonal: false,
      benefits: {},
      annualGains: { communication: 2, analysis: 3, technology: 2 }, location: 'city', hasPension: false, easeOfGetting: 4,
    },
    {
      title: 'Statistician',
      requirements: { educationIds: [...byName('Data Science','bachelors','masters','doctorate'), ...byName('Statistics','bachelors','masters','doctorate'), ...byName('Business','bachelors','masters','doctorate')], skills: { communication: 75, math: 40, technology: 15 } },
      baseSalary: 0, raiseSchedule: { type: 'MM', byDegree: { bachelors: 55000, masters: 75000, phd: 100000 } }, timeBlocks: 20, stressLevel: 30, ptoTimeBlocks: pto(10),
      fullTime: true, partTime: false, seasonal: false,
      benefits: {},
      annualGains: { communication: 2 }, location: 'city', hasPension: false, easeOfGetting: 5,
    },
    {
      title: 'Astronaut',
      requirements: { educationIds: [pid('Astronaut Academy', 'certificate'), ...byType('doctorate')], skills: { bravery: 80, caution: 90, stressTolerance: 85, physicalAbility: 60, communication: 65, technology: 40, homeRepair: 50, health: 90 }, certifications: ['CPR'], other: 'math OR science >= 75' },
      baseSalary: 0, raiseSchedule: { type: 'MS', byDegree: { masters: 65000, phd: 145000 } }, timeBlocks: 24, stressLevel: 70, ptoTimeBlocks: pto(15),
      fullTime: true, partTime: false, seasonal: false,
      benefits: {},
      annualGains: { health: -1 }, location: 'city', hasPension: true, easeOfGetting: 5,
    },
    {
      title: 'Pilot',
      requirements: { educationIds: [...byType('masters'), ...byType('doctorate')], educationAlso: [pid('Flight School', 'certificate')], skills: { bravery: 60, caution: 90, technology: 20, health: 70 }, certifications: ['CPR'] },
      baseSalary: 0, raiseSchedule: { type: 'SM', byDegree: { masters: 80000, phd: 120000 } }, timeBlocks: 24, stressLevel: 50, ptoTimeBlocks: pto(10),
      fullTime: true, partTime: true, seasonal: false,
      benefits: { travelTickets: { count: 8, discountPct: 80 } },
      annualGains: {}, location: 'city', hasPension: false, easeOfGetting: 5,
    },
    {
      title: 'Chemist',
      requirements: { educationIds: byName('Chemistry', 'bachelors', 'masters', 'doctorate'), skills: { organization: 80, caution: 80, science: 30, analysis: 30, technology: 20 } },
      baseSalary: 0, raiseSchedule: { type: 'ML', byDegree: { bachelors: 55000, masters: 65000, phd: 80000 } }, timeBlocks: 20, stressLevel: 50, ptoTimeBlocks: pto(10),
      fullTime: true, partTime: false, seasonal: false,
      benefits: {},
      annualGains: { analysis: 2 }, location: 'city', hasPension: false, easeOfGetting: 3,
    },
    {
      title: 'Software Developer',
      requirements: { educationIds: byName('Computer Science', 'bachelors', 'masters', 'doctorate'), skills: { perseverance: 55, creativity: 70, technology: 40, math: 30 } },
      baseSalary: 0, raiseSchedule: { type: 'FM', byDegree: { bachelors: 75000, masters: 100000, phd: 120000 } }, timeBlocks: 20, stressLevel: 30, ptoTimeBlocks: pto(15),
      fullTime: true, partTime: true, seasonal: false,
      benefits: { techDiscountPct: 50 },
      annualGains: { perseverance: 1, creativity: 1, technology: 3 }, location: 'city', hasPension: false, easeOfGetting: 5,
    },
    {
      title: 'Geologist',
      requirements: { educationIds: [...byName('Earth Science','bachelors'), ...byName('Geology','masters','doctorate')], skills: { organization: [50,65,80], caution: 55, science: [30,50,100], analysis: [30,50,100] } },
      baseSalary: 0, raiseSchedule: { type: 'MM', byDegree: { bachelors: 60000, masters: 80000, phd: 100000 } }, timeBlocks: 20, stressLevel: 30, ptoTimeBlocks: pto(10),
      fullTime: true, partTime: false, seasonal: false,
      benefits: {},
      annualGains: { analysis: 2 }, location: 'both', hasPension: false, easeOfGetting: 2,
    },
    {
      title: 'Climatologist',
      requirements: { educationIds: [...byName('Earth Science','bachelors'), ...byName('Climatology','masters','doctorate')], skills: { organization: [50,65,80], science: [30,50,100], writing: [30,50,100], analysis: [30,50,100] } },
      baseSalary: 0, raiseSchedule: { type: 'MM', byDegree: { bachelors: 70000, masters: 90000, phd: 110000 } }, timeBlocks: 20, stressLevel: 40, ptoTimeBlocks: 0,
      fullTime: true, partTime: false, seasonal: false,
      benefits: {},
      annualGains: { analysis: 2, writing: 1, technology: 1 }, location: 'city', hasPension: false, easeOfGetting: 3,
    },
    {
      title: 'Ecologist',
      requirements: { educationIds: [...byName('Environmental Science','bachelors'), ...byName('Ecology','masters','doctorate')], skills: { organization: [50,65,80], caution: 50, science: [30,50,100], analysis: [30,50,100] } },
      baseSalary: 0, raiseSchedule: { type: 'MM', byDegree: { bachelors: 60000, masters: 80000, phd: 100000 } }, timeBlocks: 20, stressLevel: 40, ptoTimeBlocks: pto(10),
      fullTime: true, partTime: false, seasonal: false,
      benefits: {},
      annualGains: { analysis: 2 }, location: 'both', hasPension: false, easeOfGetting: 3,
    },
    {
      title: 'Botanist',
      requirements: { educationIds: [...byName('Environmental Science','bachelors'), ...byName('Botany','masters','doctorate')], skills: { organization: [50,65,80], caution: 50, science: [30,50,100], analysis: [30,50,100] } },
      baseSalary: 0, raiseSchedule: { type: 'MM', byDegree: { bachelors: 35000, masters: 55000, phd: 80000 } }, timeBlocks: 20, stressLevel: 40, ptoTimeBlocks: pto(10),
      fullTime: true, partTime: false, seasonal: false,
      benefits: {},
      annualGains: { analysis: 2 }, location: 'both', hasPension: false, easeOfGetting: 3,
    },
    {
      title: 'Veterinarian',
      requirements: { educationIds: byName('Veterinary Studies', 'masters', 'doctorate'), skills: { compassion: 70, organization: 60, caution: 70, patience: 50, science: 50, analysis: 50, technology: 15 } },
      baseSalary: 0, raiseSchedule: { type: 'SL', byDegree: { masters: 90000, phd: 95000 } }, timeBlocks: 20, stressLevel: 50, ptoTimeBlocks: pto(15),
      fullTime: true, partTime: false, seasonal: false,
      benefits: { freeVetFees: true },
      annualGains: { analysis: 1 }, location: 'both', hasPension: false, easeOfGetting: 2,
    },
    {
      title: 'Zoologist',
      requirements: { educationIds: [...byName('Animal Science','bachelors'), ...byName('Zoology','masters','doctorate')], skills: { organization: [50,65,80], caution: 50, science: [30,50,100], analysis: [30,50,100] } },
      baseSalary: 0, raiseSchedule: { type: 'MM', byDegree: { bachelors: 40000, masters: 65000, phd: 70000 } }, timeBlocks: 20, stressLevel: 30, ptoTimeBlocks: pto(10),
      fullTime: true, partTime: false, seasonal: false,
      benefits: { zooDiscount: { freeTickets: 4, additionalPct: 50 } },
      annualGains: { analysis: 2 }, location: 'city', hasPension: false, easeOfGetting: 3,
    },
    {
      title: 'Marine Biologist',
      requirements: { educationIds: [...byName('Animal Science','bachelors'), ...byName('Marine Biology','masters','doctorate')], skills: { organization: [50,65,80], caution: 65, science: [30,50,100], analysis: [30,50,100], technology: 15 } },
      baseSalary: 0, raiseSchedule: { type: 'MM', byDegree: { bachelors: 55000, masters: 65000, phd: 75000 } }, timeBlocks: 20, stressLevel: 40, ptoTimeBlocks: pto(10),
      fullTime: true, partTime: false, seasonal: false,
      benefits: { aquariumDiscount: { freeTickets: 4, additionalPct: 50 } },
      annualGains: { analysis: 2 }, location: 'city', hasPension: false, easeOfGetting: 4,
    },
    {
      title: 'Anthropologist',
      requirements: { educationIds: byName('Anthropology', 'masters', 'doctorate'), skills: { organization: [65,80], science: [60,100], analysis: [60,100] } },
      baseSalary: 0, raiseSchedule: { type: 'MM', byDegree: { masters: 80000, phd: 100000 } }, timeBlocks: 20, stressLevel: 30, ptoTimeBlocks: 0,
      fullTime: true, partTime: false, seasonal: false,
      benefits: {},
      annualGains: { analysis: 2 }, location: 'city', hasPension: false, easeOfGetting: 5,
    },
    {
      title: 'Cybersecurity Analyst',
      requirements: { educationIds: byName('Cybersecurity', 'masters', 'doctorate'), skills: { organization: 70, caution: 70, analysis: 55, technology: 55 } },
      baseSalary: 0, raiseSchedule: { type: 'FM', byDegree: { masters: 90000, phd: 120000 } }, timeBlocks: 20, stressLevel: 50, ptoTimeBlocks: pto(10),
      fullTime: true, partTime: false, seasonal: false,
      benefits: {},
      annualGains: { analysis: 2, technology: 1 }, location: 'city', hasPension: false, easeOfGetting: 4,
    },
    {
      title: 'AI Researcher',
      requirements: { educationIds: byName('Artificial Intelligence', 'doctorate'), skills: { creativity: 80, organization: 80, communication: 75, math: 100, writing: 100, technology: 100 } },
      baseSalary: 150000, raiseSchedule: { type: 'ML' }, timeBlocks: 20, stressLevel: 40, ptoTimeBlocks: pto(15),
      fullTime: true, partTime: false, seasonal: false,
      benefits: {},
      annualGains: { creativity: 2, communication: 1 }, location: 'city', hasPension: false, easeOfGetting: 3,
    },
    {
      title: 'Pharmacist',
      requirements: { educationIds: [pid('Pharmacy School', 'certificate')], skills: { organization: 85, caution: 75, science: 50 }, certifications: ['CPR'] },
      baseSalary: 90000, raiseSchedule: { type: 'MM' }, timeBlocks: 20, stressLevel: 40, ptoTimeBlocks: pto(30),
      fullTime: true, partTime: true, seasonal: false,
      benefits: {},
      annualGains: {}, location: 'both', hasPension: false, easeOfGetting: 3,
    },
    {
      title: 'Computer Engineer',
      requirements: { educationIds: [...byName('Computer Science','bachelors'), ...byName('Computer Engineering','masters','doctorate')], skills: { organization: 80, math: 30, science: 30, homeRepair: 10, technology: 30 } },
      baseSalary: 0, raiseSchedule: { type: 'ML', byDegree: { bachelors: 70000, masters: 90000, phd: 120000 } }, timeBlocks: 20, stressLevel: 30, ptoTimeBlocks: pto(10),
      fullTime: true, partTime: false, seasonal: false,
      benefits: { techDiscountPct: 50 },
      annualGains: {}, location: 'city', hasPension: false, easeOfGetting: 3,
    },
    {
      title: 'Paramedic',
      requirements: { educationIds: byName('Biology', 'associates', 'bachelors', 'masters', 'doctorate'), skills: { compassion: 50, organization: 80, stressTolerance: 75, communication: 80, science: 15 }, certifications: ['CPR'] },
      baseSalary: 0, raiseSchedule: { type: 'MS', byDegree: { cc: 40000, bachelors: 45000, masters: 50000, phd: 60000 } }, timeBlocks: 24, stressLevel: 70, ptoTimeBlocks: pto(10),
      fullTime: true, partTime: true, seasonal: false,
      benefits: {},
      annualGains: { technology: 1, stressTolerance: 3, communication: 1 }, location: 'both', hasPension: true, easeOfGetting: 2,
    },
    {
      title: 'CSI',
      requirements: { educationIds: [...byName('Criminology','bachelors','masters','doctorate'), ...byName('Chemistry','bachelors','masters','doctorate'), ...byName('Computer Science','bachelors','masters','doctorate')], skills: { organization: 80, caution: 70, analysis: 40 }, other: 'math OR science OR tech >= 35' },
      baseSalary: 0, raiseSchedule: { type: 'MS', byDegree: { bachelors: 40000, masters: 60000, phd: 80000 } }, timeBlocks: 20, stressLevel: 50, ptoTimeBlocks: pto(15),
      fullTime: true, partTime: false, seasonal: false,
      benefits: {},
      annualGains: { analysis: 2 }, location: 'city', hasPension: true, easeOfGetting: 4,
    },
    {
      title: 'Social Worker',
      requirements: { educationIds: byName('Sociology', 'bachelors', 'masters', 'doctorate'), skills: { sociability: 70, compassion: 80, patience: 70, goodWithKids: 80, communication: 75 }, certifications: ['CPR'] },
      baseSalary: 0, raiseSchedule: { type: 'SS', byDegree: { bachelors: 55000, masters: 65000, phd: 75000 } }, timeBlocks: 20, stressLevel: 55, ptoTimeBlocks: pto(10),
      fullTime: true, partTime: false, seasonal: false,
      benefits: {},
      annualGains: { patience: 2, goodWithKids: 2 }, location: 'city', hasPension: true, easeOfGetting: 4,
    },
    {
      title: 'Optometrist',
      requirements: { educationIds: [pid('Optometry School', 'certificate')], skills: { organization: 50, caution: 70, science: 50, analysis: 40, technology: 15 }, certifications: ['CPR'] },
      baseSalary: 120000, raiseSchedule: { type: 'MM' }, timeBlocks: 20, stressLevel: 40, ptoTimeBlocks: pto(15),
      fullTime: true, partTime: false, seasonal: false,
      benefits: {},
      annualGains: { analysis: 1 }, location: 'city', hasPension: false, easeOfGetting: 2,
    },
    {
      title: 'Nanny',
      requirements: { education: 'none', skills: { charisma: 60, compassion: 80, creativity: 50, organization: 65, patience: 80, caution: 75, goodWithKids: 85 }, certifications: ['CPR'] },
      baseSalary: 25000, raiseSchedule: { type: 'MS' }, timeBlocks: 24, stressLevel: 60, ptoTimeBlocks: 0,
      fullTime: true, partTime: false, seasonal: false,
      benefits: {},
      annualGains: { creativity: 2, organization: 1, patience: 1, goodWithKids: 2 }, location: 'both', hasPension: false, easeOfGetting: 1,
    },
    {
      title: 'Animator',
      requirements: { educationIds: [...byName('Computer Science','bachelors','masters','doctorate'), ...byName('Graphic Design','bachelors','masters','doctorate'), ...byName('Digital Art','bachelors','masters','doctorate')], skills: { creativity: [70,80,95], technology: [35,55,100] } },
      baseSalary: 0, raiseSchedule: { type: 'FM', byDegree: { bachelors: 65000, masters: 85000, phd: 110000 } }, timeBlocks: 20, stressLevel: 30, ptoTimeBlocks: pto(20),
      fullTime: true, partTime: true, seasonal: false,
      benefits: {},
      annualGains: { creativity: 2, technology: 1 }, location: 'city', hasPension: false, easeOfGetting: 4,
    },
    {
      title: 'Video Game Designer',
      requirements: { educationIds: byName('Computer Science', 'bachelors', 'masters', 'doctorate'), skills: { creativity: [70,80,95], math: [30,50,100], technology: [35,55,100] } },
      baseSalary: 0, raiseSchedule: { type: 'FM', byDegree: { bachelors: 65000, masters: 75000, phd: 85000 } }, timeBlocks: 20, stressLevel: 30, ptoTimeBlocks: pto(10),
      fullTime: true, partTime: false, seasonal: false,
      benefits: {},
      annualGains: { creativity: 2, technology: 1 }, location: 'city', hasPension: false, easeOfGetting: 4,
    },
    {
      title: 'Paralegal',
      requirements: { educationIds: [...byName('English','associates','bachelors','masters','doctorate'), ...byName('Criminology','associates','bachelors','masters','doctorate'), ...byName('Sociology','associates','bachelors','masters','doctorate')], skills: { organization: [55,55,65,65], sociability: 60, analysis: [15,15,40,40], writing: [20,20,60,60] } },
      baseSalary: 0, raiseSchedule: { type: 'SM', byDegree: { cc: 55000, bachelors: 60000, masters: 70000, phd: 80000 } }, timeBlocks: 24, stressLevel: 60, ptoTimeBlocks: pto(10),
      fullTime: true, partTime: false, seasonal: false,
      benefits: {},
      annualGains: { organization: 1, analysis: 1, writing: 2 }, location: 'city', hasPension: false, easeOfGetting: 2,
    },
    {
      title: 'Reporter',
      requirements: { educationIds: [...byName('English','bachelors','masters','doctorate'), ...byName('Sociology','bachelors','masters','doctorate')], skills: { charisma: 70, communication: 40 } },
      baseSalary: 0, raiseSchedule: { type: 'MS', byDegree: { bachelors: 35000, masters: 40000, phd: 45000 } }, timeBlocks: 16, stressLevel: 30, ptoTimeBlocks: pto(10),
      fullTime: true, partTime: false, seasonal: false,
      benefits: {},
      annualGains: { communication: 1 }, location: 'city', hasPension: false, easeOfGetting: 4,
    },
    {
      title: 'Journalist',
      requirements: { educationIds: [...byName('English','bachelors','masters','doctorate'), ...byName('Sociology','bachelors','masters','doctorate')], skills: { organization: 45, writing: 20 } },
      baseSalary: 0, raiseSchedule: { type: 'MS', byDegree: { bachelors: 35000, masters: 40000, phd: 45000 } }, timeBlocks: 20, stressLevel: 30, ptoTimeBlocks: pto(10),
      fullTime: true, partTime: true, seasonal: false,
      benefits: { canBeSecondJob: true },
      annualGains: {}, location: 'both', hasPension: false, easeOfGetting: 4,
    },
    {
      title: 'Marketing Specialist',
      requirements: { educationIds: [...byName('English','bachelors','masters','doctorate'), ...byName('Sociology','bachelors','masters','doctorate'), ...byName('Business','bachelors','masters','doctorate')], skills: { charisma: 70, creativity: [70,80,95], communication: [40,50,60], analysis: [18,40,100] } },
      baseSalary: 0, raiseSchedule: { type: 'ML', byDegree: { bachelors: 55000, masters: 70000, phd: 90000 } }, timeBlocks: 20, stressLevel: 30, ptoTimeBlocks: pto(10),
      fullTime: true, partTime: false, seasonal: false,
      benefits: {},
      annualGains: { creativity: 2, communication: 2, analysis: 2 }, location: 'city', hasPension: false, easeOfGetting: 3,
    },
    {
      title: 'Paleontologist',
      requirements: { educationIds: byName('Paleontology', 'masters', 'doctorate'), skills: { organization: [65,80], patience: 75, caution: 60, analysis: [50,100], communication: [50,100], writing: [50,100], technology: 15 } },
      baseSalary: 0, raiseSchedule: { type: 'MM', byDegree: { masters: 65000, phd: 100000 } }, timeBlocks: 20, stressLevel: 40, ptoTimeBlocks: pto(10),
      fullTime: true, partTime: false, seasonal: false,
      benefits: {},
      annualGains: { patience: 2, communication: 1, writing: 1 }, location: 'city', hasPension: false, easeOfGetting: 5,
    },
    {
      title: 'Geneticist',
      requirements: { educationIds: byName('Genetics', 'masters', 'doctorate'), skills: { organization: 70, caution: 65, science: 50, analysis: 40, technology: 20 } },
      baseSalary: 0, raiseSchedule: { type: 'FM', byDegree: { masters: 45000, phd: 125000 } }, timeBlocks: 20, stressLevel: 40, ptoTimeBlocks: pto(15),
      fullTime: true, partTime: false, seasonal: false,
      benefits: {},
      annualGains: { analysis: 2 }, location: 'city', hasPension: false, easeOfGetting: 4,
    },
    {
      title: 'Astrophysicist',
      requirements: { educationIds: byName('Astrophysics', 'masters', 'doctorate'), skills: { perseverance: 75, organization: 65, caution: 90, math: [70,100], science: [70,100], analysis: [60,100], technology: 30 } },
      baseSalary: 0, raiseSchedule: { type: 'ML', byDegree: { masters: 80000, phd: 100000 } }, timeBlocks: 24, stressLevel: 60, ptoTimeBlocks: pto(15),
      fullTime: true, partTime: false, seasonal: false,
      benefits: {},
      annualGains: { perseverance: 1, analysis: 2 }, location: 'city', hasPension: false, easeOfGetting: 5,
    },
    {
      title: 'Nature Conservationist',
      requirements: { educationIds: [...byName('Environmental Science','bachelors'), ...byName('Biology','bachelors'), ...byName('Nature Conservation','masters','doctorate')], skills: { perseverance: 50, compassion: 70, communication: 50, science: 30 } },
      baseSalary: 0, raiseSchedule: { type: 'MS', byDegree: { bachelors: 60000, masters: 70000, phd: 75000 } }, timeBlocks: 20, stressLevel: 30, ptoTimeBlocks: pto(15),
      fullTime: true, partTime: false, seasonal: false,
      benefits: {},
      annualGains: { perseverance: 1, communication: 2 }, location: 'city', hasPension: false, easeOfGetting: 3,
    },
    {
      title: 'Epidemiologist',
      requirements: { educationIds: byName('Epidemiology', 'masters', 'doctorate'), skills: { organization: [65,80], caution: 70, science: [50,100], analysis: [50,100] } },
      baseSalary: 0, raiseSchedule: { type: 'ML', byDegree: { masters: 50000, phd: 80000 } }, timeBlocks: 20, stressLevel: 50, ptoTimeBlocks: pto(15),
      fullTime: true, partTime: false, seasonal: false,
      benefits: {},
      annualGains: { analysis: 1 }, location: 'city', hasPension: false, easeOfGetting: 4,
    },
    {
      title: 'Neurobiologist',
      requirements: { educationIds: byName('Neurobiology', 'doctorate'), skills: { organization: 80, caution: 55, science: 100, analysis: 100, technology: 30 } },
      baseSalary: 75000, raiseSchedule: { type: 'FM' }, timeBlocks: 20, stressLevel: 50, ptoTimeBlocks: pto(10),
      fullTime: true, partTime: false, seasonal: false,
      benefits: {},
      annualGains: {}, location: 'city', hasPension: false, easeOfGetting: 4,
    },
  ];

  for (const j of jobs) {
    const data = {
      requirements: j.requirements as object,
      baseSalary: (j.baseSalary as number) ?? 0,
      raiseSchedule: j.raiseSchedule as object,
      timeBlocks: j.timeBlocks as number,
      stressLevel: j.stressLevel as number,
      ptoTimeBlocks: (j as any).ptoTimeBlocks as number,
      fullTime: j.fullTime as boolean,
      partTime: j.partTime as boolean,
      seasonal: j.seasonal as boolean,
      benefits: j.benefits as object,
      annualGains: j.annualGains as object,
      location: j.location as string,
      hasPension: j.hasPension as boolean,
      easeOfGetting: j.easeOfGetting as number,
    };
    await prisma.job.upsert({
      where: { title: j.title as string },
      update: data,
      create: { title: j.title as string, ...data },
    });
  }
  console.log(`  ✓ ${jobs.length} jobs`);
}
